const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, BorderStyle, WidthType } = require('docx');
const { readJsonFile } = require('./lib/jsonUtils');
const config = require('./lib/config');
const fs = require('fs');
const path = require('path');

const reportDate = new Date().toISOString().split('T')[0];
const reportsDir = path.join(__dirname, 'reports');

// Default Page Layout (US Letter matching master report)
const DEFAULT_DOCUMENT_CONFIG = {
    creator: "KiteMCP Intelligence",
    description: "Individual AI Scan Report",
    styles: {
        paragraphStyles: [
            { id: "Normal", name: "Normal", run: { font: "Arial", size: 22 } },
            { id: "Heading1", name: "Heading 1", basedOn: "Normal", run: { font: "Arial", size: 32, bold: true, color: "1F4E79" }, paragraph: { spacing: { before: 240, after: 120 } } },
            { id: "Heading2", name: "Heading 2", basedOn: "Normal", run: { font: "Arial", size: 28, bold: true, color: "2E74B5" }, paragraph: { spacing: { before: 240, after: 120 } } }
        ]
    }
};

/**
 * Common Header generating logic
 */
function createHeader(title, subtitle = "") {
    const sections = [
        new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [
                new TextRun({ text: title, color: "1F4E79", size: 36, bold: true })
            ],
            alignment: "center"
        }),
        new Paragraph({
            children: [
                new TextRun({ text: `Date: ${reportDate} | Generated by: KiteMCP Agents`, italics: true, color: "595959", size: 24 })
            ],
            alignment: "center",
            spacing: { after: 240 }
        })
    ];

    if (subtitle) {
        sections.push(new Paragraph({
            children: [new TextRun({ text: subtitle, bold: true })],
            spacing: { after: 120 }
        }));
    }

    return sections;
}

/**
 * Standard Cell generating logic
 */
function stdCell(text, bold = false, color = "000000") {
    return new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: text || "-", bold: bold, color: color, font: "Arial", size: 20 })] })],
        margins: { top: 60, bottom: 60, left: 60, right: 60 }
    });
}

// ==============================================================================
// 1. Portfolio Snapshot Generator
// ==============================================================================
async function generatePortfolioSnapshot() {
    const data = readJsonFile(path.join(reportsDir, `${reportDate}_portfolio_snapshot.json`));
    if (!data) return;

    const doc = new Document({
        ...DEFAULT_DOCUMENT_CONFIG,
        sections: [{
            properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
            children: [
                ...createHeader("Portfolio Morning Scan"),
                new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun("Summary")] }),
                new Paragraph({ children: [new TextRun(`Total Available Margin: ₹${data.margin?.available?.toLocaleString('en-IN') || "N/A"}`)] }),
                new Paragraph({ children: [new TextRun(`Total Portfolio Value: ₹${Math.round(data.total_value || 0).toLocaleString('en-IN')}`)] }),
                new Paragraph({ children: [new TextRun(`Unrealized P&L: ₹${Math.round(data.total_pnl || 0).toLocaleString('en-IN')}`)] }),
                new Paragraph({ children: [new TextRun(`Day P&L: ₹${Math.round(data.day_pnl || 0).toLocaleString('en-IN')}`)] }),
                
                new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun("Holdings Breakdown")] }),
                new Table({
                    width: { size: 9360, type: WidthType.DXA },
                    columnWidths: [1500, 1000, 1500, 1500, 1500, 1500],
                    rows: [
                        new TableRow({ children: [stdCell("Symbol", true), stdCell("Qty", true), stdCell("Avg ₹", true), stdCell("CMP ₹", true), stdCell("Total ₹", true), stdCell("P&L", true)], tableHeader: true }),
                        ...(data.holdings || []).map(h => {
                            const pnlColor = h.pnl >= 0 ? "00b050" : "FF0000";
                            return new TableRow({
                                children: [
                                    stdCell(h.symbol),
                                    stdCell(h.quantity?.toString() || h.qty?.toString()),
                                    stdCell(h.average_price?.toFixed(2)),
                                    stdCell(h.last_price?.toFixed(2)),
                                    stdCell(Math.round((h.quantity || h.qty) * h.last_price).toString()),
                                    stdCell(`₹${Math.round(h.pnl)} (${h.pnl_percent?.toFixed(1) || h.pnl_pct?.toFixed(1)}%)`, true, pnlColor)
                                ]
                            });
                        })
                    ]
                })
            ]
        }]
    });

    const buffer = await Packer.toBuffer(doc);
    fs.writeFileSync(path.join(reportsDir, `${reportDate}_portfolio_report.docx`), buffer);
    console.log(`✅ Generated ${reportDate}_portfolio_report.docx`);
}

// ==============================================================================
// 2. Value Screen Generator
// ==============================================================================
async function generateValueScreen() {
    const data = readJsonFile(path.join(reportsDir, `${reportDate}_value_screen.json`));
    if (!data) return;

    const doc = new Document({
        ...DEFAULT_DOCUMENT_CONFIG,
        sections: [{
            properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
            children: [
                ...createHeader("Intrinsic Value Screen"),
                new Paragraph({ children: [new TextRun(`Methodology: Multi-model (Graham Number, DCF, PE Mean Reversion)`)] }),
                new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun("Deep Discount Stocks (MoS > 25%)")] }),
                ...((data.stocks?.filter(s => s.margin_of_safety > 25) || []).map(s => {
                    return new Paragraph({ children: [
                        new TextRun({ text: `${s.symbol} | CMP: ₹${s.current_price} | Intrinsic Value: ₹${s.intrinsic_value}`, bold: true}),
                        new TextRun({ text: `Margin of Safety: ${s.margin_of_safety}% | Signal: ${s.action_signal}`, break: 1 })
                    ], spacing: { after: 150 }});
                })),
                
                new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun("Overvalued Stocks (MoS < 0%)")] }),
                 ...((data.stocks?.filter(s => s.margin_of_safety < 0) || []).map(s => {
                    return new Paragraph({ children: [
                        new TextRun({ text: `${s.symbol} | CMP: ₹${s.current_price} | Intrinsic Value: ₹${s.intrinsic_value}`, bold: true}),
                        new TextRun({ text: `Margin of Safety: ${s.margin_of_safety}% | Signal: ${s.action_signal}`, break: 1 })
                    ], spacing: { after: 150 }});
                }))
            ]
        }]
    });

    const buffer = await Packer.toBuffer(doc);
    fs.writeFileSync(path.join(reportsDir, `${reportDate}_value_screen_report.docx`), buffer);
    console.log(`✅ Generated ${reportDate}_value_screen_report.docx`);
}

// ==============================================================================
// 3. GTT Audit Generator
// ==============================================================================
async function generateGTTAudit() {
    const data = readJsonFile(path.join(reportsDir, `${reportDate}_gtt_audit.json`));
    if (!data) return;

    const doc = new Document({
        ...DEFAULT_DOCUMENT_CONFIG,
        sections: [{
            properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
            children: [
                ...createHeader("GTT Order Audit"),
                new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun("GTT Coverage")] }),
                new Paragraph({ children: [new TextRun({ text: `Total Active GTTs: ${data.total_gtts || 0}` })] }),
                new Paragraph({ children: [new TextRun({ text: `Holdings Protected: ${data.protected_holdings || 0}` })] }),
                new Paragraph({ children: [new TextRun({ text: "Unprotected Holdings:", bold: true, color: "FF0000" })] }),
                ...(data.unprotected_holdings?.length > 0 ? data.unprotected_holdings.map(h => new Paragraph({ children: [new TextRun(`• ${h.symbol}`)], indent: { left: 360 } })) : [new Paragraph({ children: [new TextRun("All holdings have protective stop-losses!")] })]),
                
                new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun("Active GTT Orders")] }),
                new Table({
                    width: { size: 9360, type: WidthType.DXA },
                    columnWidths: [1500, 1500, 1500, 1500, 3360],
                    rows: [
                        new TableRow({ children: [stdCell("Symbol", true), stdCell("Type", true), stdCell("Trigger ₹", true), stdCell("CMP ₹", true), stdCell("Status/Note", true)], tableHeader: true }),
                        ...(data.active_gtts || []).map(g => {
                            let note = "Active";
                            if (g.stale || g.is_stale) note = "⚠️ STALE - NEEDS REVIEW";
                            if (g.gap_percent > 20) note = `⚠️ trigger >20% away (${g.gap_percent}%)`;
                            return new TableRow({
                                children: [stdCell(g.symbol), stdCell(g.type), stdCell(g.trigger_price?.toString()), stdCell(g.current_price?.toString()), stdCell(note)]
                            });
                        })
                    ]
                })
            ]
        }]
    });

    const buffer = await Packer.toBuffer(doc);
    fs.writeFileSync(path.join(reportsDir, `${reportDate}_gtt_audit_report.docx`), buffer);
    console.log(`✅ Generated ${reportDate}_gtt_audit_report.docx`);
}

// ==============================================================================
// 4. Opportunities Generator (Equities)
// ==============================================================================
async function generateOpportunities() {
    const data = readJsonFile(path.join(reportsDir, `${reportDate}_opportunities.json`));
    if (!data) return;

    const doc = new Document({
        ...DEFAULT_DOCUMENT_CONFIG,
        sections: [{
            properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
            children: [
                ...createHeader("Investment Opportunities Scanner"),
                new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun("Web-Scanned Stock Opportunities")] }),
                ...(data.opportunities || []).map(o => {
                    return new Paragraph({
                        children: [
                            new TextRun({ text: `${o.symbol} [${o.horizon}]`, bold: true, size: 28, color: "2E7D32" }),
                            new TextRun({ text: `CMP: ₹${o.current_price || "N/A"}`, break: 1 }),
                            new TextRun(`  |  Target: ₹${o.target_3m || o.target || "N/A"} (${o.upside_3m || o.upside_percent || ""}% Upside)`),
                            new TextRun({ text: `Recommendation: `, break: 1 }),
                            new TextRun({ text: o.recommendation, bold: true, color: o.recommendation?.includes("BUY") ? "00b050" : "000000" }),
                            new TextRun({ text: `Catalyst: ${o.catalyst}`, break: 1 }),
                            new TextRun({ text: `PE Ratio: ${o.pe_ratio || "N/A"}  |  ROE: ${o.roe || "N/A"}`, break: 1 }),
                        ],
                        spacing: { after: 300 }
                    });
                })
            ]
        }]
    });

    const buffer = await Packer.toBuffer(doc);
    fs.writeFileSync(path.join(reportsDir, `${reportDate}_opportunities_report.docx`), buffer);
    console.log(`✅ Generated ${reportDate}_opportunities_report.docx`);
}

// ==============================================================================
// 5. Commodity Opportunities Generator
// ==============================================================================
async function generateCommodities() {
    const data = readJsonFile(path.join(reportsDir, `${reportDate}_commodity_opportunities.json`));
    if (!data) return;

    const doc = new Document({
        ...DEFAULT_DOCUMENT_CONFIG,
        sections: [{
            properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
            children: [
                ...createHeader("Commodity Market Opportunities"),
                new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun("MCX Commodities Summary")] }),
                ...(data.commodities || []).map(c => {
                    const color = c.change_percent >= 0 ? "00b050" : "FF0000";
                    return new Paragraph({
                        children: [
                            new TextRun({ text: `${c.symbol || c.name}`, bold: true, size: 28 }),
                            new TextRun({ text: `Price: ₹${c.price} `, break: 1 }),
                            new TextRun({ text: `(${c.change_percent >= 0 ? "+" : ""}${c.change_percent}%)`, color: color, bold: true }),
                            new TextRun({ text: `Trend: ${c.trend}  |  Recommendation: `, break: 1 }),
                            new TextRun({ text: c.recommendation || c.action, bold: true }),
                            new TextRun({ text: `Support: ₹${c.support || "N/A"}  |  Resistance: ₹${c.resistance || "N/A"}`, break: 1 }),
                            new TextRun({ text: `Catalyst: ${c.catalyst || c.driver || "N/A"}`, break: 1 }),
                        ],
                        spacing: { after: 300 }
                    });
                })
            ]
        }]
    });

    const buffer = await Packer.toBuffer(doc);
    fs.writeFileSync(path.join(reportsDir, `${reportDate}_commodity_opportunities_report.docx`), buffer);
    console.log(`✅ Generated ${reportDate}_commodity_opportunities_report.docx`);
}

// ==============================================================================
// 6. News Opportunities Generator
// ==============================================================================
async function generateNewsOpportunities() {
    const data = readJsonFile(path.join(reportsDir, `${reportDate}_news_opportunities.json`));
    if (!data) return;

    const doc = new Document({
        ...DEFAULT_DOCUMENT_CONFIG,
        sections: [{
            properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
            children: [
                ...createHeader("News-Driven Opportunities"),
                new Paragraph({ children: [new TextRun({ text: `Market Mood: ${data.market_mood || "N/A"}`, bold: true, size: 24 })], spacing: { after: 240 } }),
                new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun("Impactful News Events")] }),
                ...(data.news || []).map(n => {
                    const impactColor = n.impact_score >= 8 ? "FF0000" : (n.impact_score >= 5 ? "E69138" : "000000");
                    return new Paragraph({
                        children: [
                            new TextRun({ text: `${n.symbol || n.sector || n.headline}`, bold: true, size: 28 }),
                            new TextRun({ text: ` [Impact: ${n.impact_score}/10]`, color: impactColor, bold: true }),
                            new TextRun({ text: `Sentiment: ${n.sentiment || "Neutral"}  |  Type: ${n.type}`, break: 1 }),
                            new TextRun({ text: `Headline: `, break: 1 }),
                            new TextRun({ text: n.headline, italics: true }),
                            new TextRun({ text: `Catalyst / Takeaway: ${n.catalyst || n.summary}`, break: 1 }),
                            new TextRun({ text: `Action: `, break: 1 }),
                            new TextRun({ text: n.recommendation || n.action_signal, bold: true }),
                        ],
                        spacing: { after: 300 }
                    });
                })
            ]
        }]
    });

    const buffer = await Packer.toBuffer(doc);
    fs.writeFileSync(path.join(reportsDir, `${reportDate}_news_opportunities_report.docx`), buffer);
    console.log(`✅ Generated ${reportDate}_news_opportunities_report.docx`);
}

// ==============================================================================
// Run All
// ==============================================================================
async function runAll() {
    console.log("Generating Indivdual Deep-Dive Reports...");
    await generatePortfolioSnapshot().catch(e => console.error(e));
    await generateValueScreen().catch(e => console.error(e));
    await generateGTTAudit().catch(e => console.error(e));
    await generateOpportunities().catch(e => console.error(e));
    await generateCommodities().catch(e => console.error(e));
    await generateNewsOpportunities().catch(e => console.error(e));
    console.log("✅ All individual reports generated.");
}

runAll();
